name: bios6642
channels:
  - microsoft
  - conda-forge
  - defaults
dependencies:
  - certifi=2021.10.8
  - jupyterlab=3.3.2
  - jupytext=1.13.8
  - lxml=4.8.0
  - pandas=1.4.2
  - pip=21.2.4
  - playwright=v1.18.1
  - python=3.9.12
  - selenium=3.141.0
  - tzdata=2022a
  - pip:
    - requests-html==0.10.0
